[env]
TERM = "xterm-256color"

[window.dimensions]
columns = 120
lines = 80

[window]
decorations = "None"
opacity = 0.95
startup_mode = "Maximized"
dynamic_title = false

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font]
size = 12.0
builtin_box_drawing = false

# Colors (Gruvbox dark)

[colors]
transparent_background_colors = true

# Default colors
[colors.primary]
# hard contrast background = = "#1d2021"
# normal contrast background = = "#282828"
# soft contrast background = = "#32302f"
background = "#1d2021"
foreground = "#ebdbb2"

# Normal colors
[colors.normal]
black   = "#282828"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

# Bright colors
[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"

[selection]
save_to_clipboard = true

[terminal.shell]
# Linux
program = "/bin/zsh"
args = [ "-l", "-c", "tmux attach || tmux" ]
# Window
# program = "cmd.exe"
# args = [ "-c", "ssh", "name@xx.xx.xx.xx" ]

[mouse]
hide_when_typing = true
bindings = [
    { mouse = "Right", action = "Paste" },
]

[keyboard]
bindings = [
    { key = "Enter", mods = "Alt", action = "ToggleFullscreen" },
    { key = "\\", mods = "Alt", action = "ToggleViMode" },
]
